### PR TITLE
Update for Angular V10

### LINKED ISSUE #41: Doesnt work with angular 10
When i´m updating to angular 10, i get following error message:

                 Package "@thisissoon/`angular-inviewport" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0 <9.0.0" (extended), would install "10.0.0").`

Please increase the peer depencency to version 10.

### PR DESCRIPTION
**Pull request by localpcguy**
fixes #41

### CODE REVIEW

**Comment by localpcguy** [comment]
cc: @thisissoon - we are upgrading to Angular v10 and this is giving us a warning

**Comment by localpcguy** [comment]
I rebased master, had to rebuild the yarn lock file. And the references in the polyfills file were incorrect for the latest version. So there is some slight changes and 1 new commit to look at.

**Comment by MollardMichael** [comment]
Hello,

The lint failed because it failed to find stylelint. I failed to find the issue. yarn is run before testing and the package.json does include styleling. Could you try rerunning it ?

**Comment by localpcguy** [comment]
@MollardMichael were you asking me to do something, or @jamesjwarren?

**Comment by localpcguy** [comment]
@MollardMichael or @jamesjwarren (not sure who to ping, sorry) - we are now upgrading to Angular v11 now and are hoping this can be merged (potentially with an update to allow v11 also). What needs to be done to make that happen?

**Comment by jamesjwarren** [comment]
Hi @localpcguy, it looks like there were some linting issues causing the CI test stage to fail, looks like these were possibly caused by prettier preset configs being updated as they're present on master as well. I've resolved the issues on master so rebasing this should now hopefully pass CI. Then I'm happy to merge this and the V11 work, thanks for updating!

**Comment by localpcguy** [comment]
Does this need an npm deployment? Looks like these changes may not be in the 4.2.2 version.

**Pull request merged**
